import { useEffect, useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { HubConnection, HubConnectionBuilder, LogLevel } from '@microsoft/signalr';
import { Button } from '@mui/material';

export default function Home() {
    const [activeConnection, setActiveConnection] = useState<HubConnection>();

    const joinSession = async (playerName: string, gameSessionId: number) => {
        try {
            const connection = new HubConnectionBuilder()
                .withUrl('http://localhost:5000/game/')
                .configureLogging(LogLevel.Information)
                .build();
            
            connection.on('ReceiveNotification', (user: string, message: string) => {
                console.log(`${user}: ${message}`); 
            });
            
            await connection.start();
            await connection.invoke('JoinSession', { playerName, gameSessionId });
            setActiveConnection(connection);
        } catch (e) {
            console.log(e);
        }
    }

    const closeConnection = async () => {
        try {
            await activeConnection?.stop();
        } catch (e) {
            console.log(e);
        }
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Button onClick={() => joinSession('Mykola', 7)}>Join</Button>
            <Button onClick={closeConnection}>Stop</Button>
        </div>
    )
}
